//! Colour configuration (modelled on slogs').
//!
//! Colours come from a config file and nowhere else — no `$TERM` tables, no
//! environment sniffing. A missing file is normal; the built-in defaults
//! apply.
//!
//! [`DEFAULT_CONFIG`] is the single source of truth: `--generate-config`
//! prints it, and the built-in defaults are produced by parsing that same
//! string, so the template and the defaults cannot drift apart. A test
//! asserts it parses with no warnings and sets every key.

use std::path::PathBuf;

use crate::theme::{Theme, parse_style};

/// The built-in defaults, and what `--generate-config` prints.
///
/// Deliberately uses the 16 ANSI colour names, which follow the terminal's own
/// palette, so the starter scheme suits a light or a dark theme without being
/// told which.
pub const DEFAULT_CONFIG: &str = r##"# wt colour configuration.
#
# Generated by `wt --generate-config`. These are the built-in defaults, so a
# fresh copy of this file changes nothing until you edit it.
#
# Location: $WT_CONFIG, else $XDG_CONFIG_HOME/wt/config.toml,
#           else ~/.config/wt/config.toml
#
#
# WHICH KEY AFFECTS WHICH PART OF THE `wt list` TABLE
# ───────────────────────────────────────────────────
#
#   PATH      BRANCH  SIZE  STATUS        MERGED  UPSTREAM  LAST
#   ../repo   main    1.2G  clean         -       ok        2 hours ago   [main] [cwd]
#   └──────┘  └────┘  └──┘  └───────────┘ └────┘  └──────┘  └─────────┘   └──────────┘
#     path    branch  size*    status*    merged* upstream*    last*        markers
#
#   Column titles use "header". The starred columns pick a key by the cell's
#   value; the tables below say which.
#
#
# WRITING A COLOUR
# ────────────────
#
# One string per setting. Space-separated, in any order:
#
#   attributes   bold  dim  italic  underline  reverse
#   default      the terminal's own foreground; use it to switch a colour off
#   a colour     in one of three notations, tried in this order:
#
#     1. an ANSI name   black red green yellow blue magenta cyan white
#                       bright-black ... bright-white
#                       These follow your terminal's palette, so a themed
#                       terminal stays consistent.
#     2. an index       0-255, a literal 256-colour palette entry
#     3. hex            #rrggbb, or #rgb
#
# Notations 1 and 2 are exact everywhere. Only hex is 24-bit: on a terminal
# without truecolor support it is approximated to the nearest palette colour.

[colour]
header           = "cyan bold"      # the column titles
path             = "bright-white"   # the PATH column
branch           = "white"          # the BRANCH column

# The [main] and [cwd] markers after a row.
marker-brackets  = "bright-white"   # the [ ] themselves
marker-main      = "bright-yellow"  # the word main
marker-cwd       = "bright-green"   # the word cwd

# SIZE (with -s), by how big the worktree is on disk.
size             = "bright-white"   # up to 1 GiB
size-warn        = "bright-yellow"  # over 1 GiB
size-alert       = "bright-red"     # over 10 GiB

# STATUS (with -g). A combined cell like "2 mod, 1 untr" paints each part.
status-clean     = "green"          # clean
status-modified  = "red"            # N mod
status-untracked = "yellow"         # N untr

# MERGED (with -g).
merged           = "green"          # merged into the main worktree's HEAD
unmerged         = "yellow"         # +N commits not yet merged

# UPSTREAM (with -g). ahead/behind counts stay uncoloured.
upstream-ok      = "green"          # in sync with the tracking ref
upstream-none    = "white"          # no upstream

# LAST (with -g), by the age of the last commit.
last-fresh       = "green"          # up to last-fresh days old
last-aging       = "yellow"         # older than that, under last-aging days
last-old         = "red"            # last-aging days old or more

# Where the SIZE and LAST colours switch over. Whole numbers.
[thresholds]
size-warn        = 1024             # MiB; SIZE bigger than this is size-warn
size-alert       = 10240            # MiB; SIZE bigger than this is size-alert
last-fresh       = 3                # days; this old or newer is last-fresh
last-aging       = 7                # days; this old or older is last-old
"##;

/// Every key accepted under `[colour]`.
pub const KEYS: &[&str] = &[
    "header",
    "path",
    "branch",
    "marker-brackets",
    "marker-main",
    "marker-cwd",
    "size",
    "size-warn",
    "size-alert",
    "status-clean",
    "status-modified",
    "status-untracked",
    "merged",
    "unmerged",
    "upstream-ok",
    "upstream-none",
    "last-fresh",
    "last-aging",
    "last-old",
];

/// Every key accepted under `[thresholds]`. `size-*` are MiB, `last-*` days.
pub const THRESHOLD_KEYS: &[&str] = &["size-warn", "size-alert", "last-fresh", "last-aging"];

const MIB: u64 = 1 << 20;

/// The result of loading configuration. Problems are warnings, never
/// failures: a broken config must not stop a listing from running.
#[derive(Debug, Default)]
pub struct Loaded {
    pub theme: Theme,
    pub warnings: Vec<String>,
}

/// The built-in defaults.
pub fn defaults() -> Theme {
    parse(DEFAULT_CONFIG).theme
}

/// Where the config file lives, if it can be determined at all.
pub fn config_path() -> Option<PathBuf> {
    resolve_path(
        std::env::var_os("WT_CONFIG"),
        std::env::var_os("XDG_CONFIG_HOME"),
        std::env::var_os("HOME"),
    )
}

/// The path rule, with the environment passed in rather than read.
///
/// Kept pure so it can be tested without mutating process-wide environment
/// variables, which would race against every other test in the binary.
fn resolve_path(
    explicit: Option<std::ffi::OsString>,
    xdg: Option<std::ffi::OsString>,
    home: Option<std::ffi::OsString>,
) -> Option<PathBuf> {
    if let Some(explicit) = explicit {
        return Some(PathBuf::from(explicit));
    }
    let base = xdg
        .map(PathBuf::from)
        .or_else(|| home.map(|h| PathBuf::from(h).join(".config")))?;
    Some(base.join("wt").join("config.toml"))
}

/// Load the defaults, then overlay the config file if there is one.
pub fn load() -> Loaded {
    let mut loaded = Loaded {
        theme: defaults(),
        warnings: Vec::new(),
    };
    let Some(path) = config_path() else {
        return loaded;
    };
    match std::fs::read_to_string(&path) {
        Ok(text) => {
            let user = parse_over(&text, &mut loaded.theme);
            loaded
                .warnings
                .extend(user.into_iter().map(|w| format!("{}: {w}", path.display())));
        }
        // Not having a config file is the normal case.
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => loaded
            .warnings
            .push(format!("cannot read {}: {e}", path.display())),
    }
    loaded
}

/// Parse config text over an unstyled theme. Only keys actually present are
/// set, so the result of parsing `DEFAULT_CONFIG` IS the default palette.
pub fn parse(text: &str) -> Loaded {
    let mut theme = Theme::default();
    let warnings = parse_over(text, &mut theme);
    Loaded { theme, warnings }
}

/// Apply config text onto `theme`, key by key, returning the warnings. A user
/// config that sets one colour leaves every other value in place.
fn parse_over(text: &str, theme: &mut Theme) -> Vec<String> {
    let mut warnings = Vec::new();

    let table: toml::Table = match text.parse() {
        Ok(t) => t,
        Err(e) => {
            warnings.push(format!("ignoring this file, it is not valid TOML: {e}"));
            return warnings;
        }
    };

    for (section, value) in &table {
        if section == "thresholds" {
            match value.as_table() {
                Some(thresholds) => parse_thresholds(thresholds, theme, &mut warnings),
                None => warnings.push("[thresholds] should be a table".to_string()),
            }
            continue;
        }
        // "color" is accepted alongside "colour" so the spelling is never a trap.
        if section != "colour" && section != "color" {
            warnings.push(format!("unknown section [{section}]"));
            continue;
        }
        let Some(colour) = value.as_table() else {
            warnings.push(format!("[{section}] should be a table"));
            continue;
        };
        for (key, value) in colour {
            if !KEYS.contains(&key.as_str()) {
                warnings.push(format!("unknown key {key:?} in [{section}]"));
                continue;
            }
            let Some(spec) = value.as_str() else {
                warnings.push(format!("{key} should be a string, such as \"red bold\""));
                continue;
            };
            match parse_style(spec) {
                Ok(style) => {
                    *theme.slot(key).expect("KEYS and slot() are in sync") = style;
                }
                Err(e) => warnings.push(format!("{key}: {e}")),
            }
        }
    }

    warnings
}

fn parse_thresholds(table: &toml::Table, theme: &mut Theme, warnings: &mut Vec<String>) {
    for (key, value) in table {
        if !THRESHOLD_KEYS.contains(&key.as_str()) {
            warnings.push(format!("unknown key {key:?} in [thresholds]"));
            continue;
        }
        let n = match value.as_integer() {
            Some(n) if n >= 0 => n as u64,
            _ => {
                warnings.push(format!(
                    "thresholds.{key} should be a whole non-negative number"
                ));
                continue;
            }
        };
        match key.as_str() {
            "size-warn" => theme.size_warn_bytes = n * MIB,
            "size-alert" => theme.size_alert_bytes = n * MIB,
            "last-fresh" => theme.last_fresh_days = n,
            "last-aging" => theme.last_aging_days = n,
            _ => unreachable!("key was checked against THRESHOLD_KEYS"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keys_and_theme_slots_are_in_sync() {
        let mut theme = Theme::default();
        for key in KEYS {
            assert!(theme.slot(key).is_some(), "no slot for config key {key:?}");
        }
    }

    #[test]
    fn default_config_parses_cleanly_and_sets_every_key() {
        let loaded = parse(DEFAULT_CONFIG);
        assert_eq!(loaded.warnings, Vec::<String>::new());
        // Every key must appear in the template: it documents the whole
        // vocabulary, and the defaults are produced by parsing it.
        for key in KEYS {
            assert!(
                DEFAULT_CONFIG.contains(key),
                "{key:?} missing from DEFAULT_CONFIG"
            );
        }
        // And the palette is styled, not the unstyled base.
        assert_ne!(loaded.theme, Theme::default());
    }

    #[test]
    fn defaults_match_the_agreed_palette() {
        let t = defaults();
        let s = |spec: &str| parse_style(spec).unwrap();
        assert_eq!(t.header, s("cyan bold"));
        assert_eq!(t.path, s("bright-white"));
        assert_eq!(t.branch, s("white"));
        assert_eq!(t.marker_brackets, s("bright-white"));
        assert_eq!(t.marker_main, s("bright-yellow"));
        assert_eq!(t.marker_cwd, s("bright-green"));
        assert_eq!(t.size, s("bright-white"));
        assert_eq!(t.size_warn, s("bright-yellow"));
        assert_eq!(t.size_alert, s("bright-red"));
        assert_eq!(t.status_clean, s("green"));
        assert_eq!(t.status_mod, s("red"));
        assert_eq!(t.status_untr, s("yellow"));
        assert_eq!(t.merged_ok, s("green"));
        assert_eq!(t.merged_unmerged, s("yellow"));
        assert_eq!(t.upstream_ok, s("green"));
        assert_eq!(t.upstream_none, s("white"));
        assert_eq!(t.last_fresh, s("green"));
        assert_eq!(t.last_aging, s("yellow"));
        assert_eq!(t.last_old, s("red"));
        // Thresholds: 1024 / 10240 MiB, 3 / 7 days.
        assert_eq!(t.size_warn_bytes, 1 << 30);
        assert_eq!(t.size_alert_bytes, 10 << 30);
        assert_eq!(t.last_fresh_days, 3);
        assert_eq!(t.last_aging_days, 7);
    }

    #[test]
    fn thresholds_can_be_overridden() {
        let mut theme = defaults();
        let warnings = parse_over(
            "[thresholds]\nsize-warn = 512\nlast-aging = 14\n",
            &mut theme,
        );
        assert_eq!(warnings, Vec::<String>::new());
        assert_eq!(theme.size_warn_bytes, 512 << 20);
        assert_eq!(theme.last_aging_days, 14);
        // Unmentioned thresholds keep their defaults.
        assert_eq!(theme.size_alert_bytes, 10 << 30);
        assert_eq!(theme.last_fresh_days, 3);
    }

    #[test]
    fn bad_thresholds_warn_and_change_nothing() {
        let mut theme = defaults();
        let warnings = parse_over(
            "[thresholds]\nsize-warn = \"big\"\nlast-fresh = -1\nbogus = 3\n",
            &mut theme,
        );
        assert_eq!(warnings.len(), 3);
        assert_eq!(theme, defaults());
    }

    #[test]
    fn user_config_overlays_one_key_and_keeps_the_rest() {
        let mut theme = defaults();
        let warnings = parse_over("[colour]\nbranch = \"red italic\"\n", &mut theme);
        assert_eq!(warnings, Vec::<String>::new());
        assert_eq!(theme.branch, parse_style("red italic").unwrap());
        assert_eq!(theme.header, parse_style("cyan bold").unwrap());
    }

    #[test]
    fn color_spelling_is_accepted() {
        let mut theme = defaults();
        let warnings = parse_over("[color]\npath = \"blue\"\n", &mut theme);
        assert_eq!(warnings, Vec::<String>::new());
        assert_eq!(theme.path, parse_style("blue").unwrap());
    }

    #[test]
    fn problems_are_warnings_never_failures() {
        let mut theme = defaults();
        let warnings = parse_over(
            "[colour]\nheader = \"no-such-colour\"\nbogus = \"red\"\npath = 3\n\n[other]\nx = 1\n",
            &mut theme,
        );
        assert_eq!(warnings.len(), 4);
        // The good defaults survive every bad key.
        assert_eq!(theme, defaults());

        let warnings = parse_over("not toml at all [", &mut theme);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("not valid TOML"));
    }

    #[test]
    fn path_rule() {
        let p = |e: Option<&str>, x: Option<&str>, h: Option<&str>| {
            resolve_path(e.map(Into::into), x.map(Into::into), h.map(Into::into))
        };
        assert_eq!(
            p(Some("/tmp/x.toml"), None, None),
            Some("/tmp/x.toml".into())
        );
        assert_eq!(
            p(None, Some("/xdg"), Some("/home/u")),
            Some("/xdg/wt/config.toml".into())
        );
        assert_eq!(
            p(None, None, Some("/home/u")),
            Some("/home/u/.config/wt/config.toml".into())
        );
        assert_eq!(p(None, None, None), None);
    }
}
